// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAvSGbsUMRPdzvJftgZUAZ5fo9OkwjS8Y',
    appId: '1:5344910601:web:d740f804506208354387d8',
    messagingSenderId: '5344910601',
    projectId: 'iti-project-3f2d7',
    authDomain: 'iti-project-3f2d7.firebaseapp.com',
    storageBucket: 'iti-project-3f2d7.appspot.com',
    measurementId: 'G-BN5LFNR9TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ISgEN-DJNri36emgFKFKAJufuI-21jI',
    appId: '1:5344910601:android:b83ca2466e0ec5844387d8',
    messagingSenderId: '5344910601',
    projectId: 'iti-project-3f2d7',
    storageBucket: 'iti-project-3f2d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjoAyFZON44BNp5EH-1VSfTjj6SdeOxXs',
    appId: '1:5344910601:ios:9188bcaa0fd77ad24387d8',
    messagingSenderId: '5344910601',
    projectId: 'iti-project-3f2d7',
    storageBucket: 'iti-project-3f2d7.appspot.com',
    iosBundleId: 'com.example.itiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjoAyFZON44BNp5EH-1VSfTjj6SdeOxXs',
    appId: '1:5344910601:ios:9188bcaa0fd77ad24387d8',
    messagingSenderId: '5344910601',
    projectId: 'iti-project-3f2d7',
    storageBucket: 'iti-project-3f2d7.appspot.com',
    iosBundleId: 'com.example.itiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAvSGbsUMRPdzvJftgZUAZ5fo9OkwjS8Y',
    appId: '1:5344910601:web:fa2922173dccafe34387d8',
    messagingSenderId: '5344910601',
    projectId: 'iti-project-3f2d7',
    authDomain: 'iti-project-3f2d7.firebaseapp.com',
    storageBucket: 'iti-project-3f2d7.appspot.com',
    measurementId: 'G-M5G0Y0CKY0',
  );
}
